### ISSUE TITLE
Assertion failing in cdgc

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/tangort#20]
If you compile tangort without `-release -O -inline` and try to run:

```
make run-dhttest
```

on the fresh checkout of master branch of https://github.com/sociomantic-tsunami/dhtnode the assertion 

https://github.com/sociomantic-tsunami/tangort/blob/v1.x.x/src/gc/cdgc/gc.d#L325

will fail:

```
nemanjaboric@labs-129:/home/nemanjaboric/work/tsunami/dhtnode  git:(master*) $ make run-dhttest
!! Flags or commands changed: D compiler; re-building affected files...
   rdmd build/devel/bin/dhtnode
   rdmd build/devel/tmp/test-dhttest
   build/devel/tmp/test-dhttest run-dhttest
/home/nemanjaboric/work/tangort/src/gc/cdgc/gc.d:325: cdgc assertion failed
Aborted (core dumped)
```

```
(gdb) bt
#0  0x00007f79314bf428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f79314c102a in __GI_abort () at abort.c:89
#2  0x0000000000a79ab2 in gc.cdgc.os.assert_!(bool).assert_(lazy bool, lazy char[], char[], ulong) (line=325, file=..., msg=0x0000000000a7a3e000007ffe01ec3c50, exp=0x0000000000a7a3b800007ffe01ec3c50)
    at /home/nemanjaboric/work/tangort/src/gc/cdgc/os.d:54
#3  0x0000000000a79fde in gc.cdgc.gc.Invariant() () at /home/nemanjaboric/work/tangort/src/gc/cdgc/os.d:42
#4  0x0000000000a7edd5 in gc.cdgc.gc.gc_collect().locked!(void, gc.cdgc.gc.gc_collect().__dgliteral117()).locked().__dgliteral117().__dgliteral355() (this=0x0)
    at /home/nemanjaboric/work/tangort/src/gc/cdgc/gc.d:2512
#5  0x0000000000a79a20 in gc.cdgc.os.assert_!(bool).assert_(lazy bool, lazy char[], char[], ulong) (line=2512, file=..., msg=0x0000000000a7eddc0000000000000000, exp=0x0000000000a7edc40000000000000000)
    at /home/nemanjaboric/work/tangort/src/gc/cdgc/os.d:46
#6  0x0000000000a7ed7e in gc.cdgc.gc.gc_collect().locked!(void, gc.cdgc.gc.gc_collect().__dgliteral117()).locked().__dgliteral117() (this=0x0) at /home/nemanjaboric/work/tangort/src/gc/cdgc/os.d:42
#7  0x0000000000a7eca8 in gc.cdgc.gc.gc_collect().locked!(void, gc.cdgc.gc.gc_collect().__dgliteral117()).locked() (this=0x0) at /home/nemanjaboric/work/tangort/src/gc/cdgc/gc.d:268
#8  0x0000000000a7c967 in gc_collect () at /home/nemanjaboric/work/tangort/src/gc/cdgc/gc.d:2516
#9  0x0000000000a7788d in core.memory.GC.collect() () at /home/nemanjaboric/work/tangort/src/core/memory.d:106
#10 0x000000000093304c in ocean.util.container.map.Map.test_key!(byte).test_key() () at ./submodules/ocean/src/ocean/util/container/map/Map.d:1185
#11 0x0000000000932f91 in ocean.util.container.map.Map.__unittestL1218_443() () at ./submodules/ocean/src/ocean/util/container/map/Map.d:1220
#12 0x0000000000945181 in ocean.util.container.map.Map.__modtest() ()
#13 0x0000000000a75c15 in core.runtime.runModuleUnitTests().__foreachbody493(ref ModuleInfo) (this=0x0, __applyArg0=0x7ffe01ec3ea8) at /home/nemanjaboric/work/tangort/src/core/runtime.d:180
#14 0x0000000000a6c7cb in object.ModuleInfo.opApply(int(ref ModuleInfo) delegate) (dg=...) at /home/nemanjaboric/work/tangort/src/rt/object_.d:1506
#15 0x0000000000a75ba9 in runModuleUnitTests () at /home/nemanjaboric/work/tangort/src/core/runtime.d:175
#16 0x0000000000a67021 in rt.dmain2.main(int, char**).runAll() (this=0x7ffe01ec4010) at /home/nemanjaboric/work/tangort/src/rt/dmain2.d:369
#17 0x0000000000a66f9a in rt.dmain2.main(int, char**).tryExec(void() delegate) (this=0x7ffe01ec4010, dg=...) at /home/nemanjaboric/work/tangort/src/rt/dmain2.d:348
#18 0x0000000000a66e7f in main (argc=1, argv=0x7ffe01ec40f8) at /home/nemanjaboric/work/tangort/src/rt/dmain2.d:377
#19 0x00007f79314aa830 in __libc_start_main (main=0xa66db4 <main>, argc=1, argv=0x7ffe01ec40f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe01ec40e8)
    at ../csu/libc-start.c:291
#20 0x00000000007ec249 in _start ()
```

Sadly I can't manage to reproduce it in a simple application.

**Comment by leandro-lucarella-sociomantic** [comment]
This is spooky and my guess is it will take quite some time to debug. Considering the GC doesn't seem to be either leaking or corrupting memory (from experience at using it), I wonder what would be the ROI of addressing this issue, specially considering that we are moving to D2.

I would check, just out of curiosity, how off both values are...

**Comment by mihails-strasuns-sociomantic** [comment]
It could also be consequence of memory corruption in app code

**Comment by nemanja-boric-sociomantic** [comment]
```
nemanjaboric@labs-129:/home/nemanjaboric/work/tsunami/dhtnode  git:(master*) $ make run-dhttest
   rdmd build/devel/bin/dhtnode
   rdmd build/devel/tmp/test-dhttest
   build/devel/tmp/test-dhttest run-dhttest
gc.free mem (900704) != free_mem (900320)
/home/nemanjaboric/work/tangort/src/gc/cdgc/gc.d:330: cdgc assertion failed
Aborted (core dumped)
```
